version: "3.8"

services:
  nginx:
    image: ghcr.io/cssnr/docker-nginx-proxy:latest
    environment:
      - SERVICE_NAME=app
      - SERVICE_PORT=3000
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 64M
    depends_on:
      - app
    ports:
      - "${PORT:-80}:80"

  app:
    build:
      context: .
    image: node-redirect:latest
    command: "npm run dev"
    environment:
      #DEBUG: "express:*"
      REDIRECTS: ${REDIRECTS}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 256M
    volumes:
      - ${APP_FILES:-./src}:/app/src
