name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    # NOTE: Look into running build.yaml and deploy.yaml inline here
    steps:
      - name: "Update Release Notes Action"
        continue-on-error: true
        uses: smashedr/update-release-notes-action@master
        with:
          location: tail

      - name: "Package Changelog Action"
        continue-on-error: true
        uses: cssnr/package-changelog-action@v1

      - name: "Send Failure Notification"
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
